-- AUTOGENERATED, DO NOT EDIT.
--
-- Source file:
-- /Users/erikrain/Source/external/nunavut/submodules/public_regulated_data_types/uavcan/node/7509.Heartbeat.1.0.dsdl
--
-- Generated at:  2024-07-19 22:00:20.127709 UTC
-- Is deprecated: no
-- Fixed port ID: 7509
-- Full name:     uavcan.node.Heartbeat
-- Version:       1.0
--
-- Type Information: Is uavcan.node.Heartbeat a ?
-- Void:          no
-- Boolean:       no
-- Primitive:     no
-- Integer:       no
-- Float:         no
-- ArrayType:     no
-- FixedLengthArray: no
-- VariableLengthArray: no
-- Composite:     yes
-- Delimited:     yes
-- Union:         no
-- Service:       no

-- We always use the generated nunavut support
local nunavut_support = require('nunavut_support')
--[[
Abstract component health information. If the node performs multiple activities (provides multiple network services),
its health status should reflect the status of the worst-performing activity (network service).
Follows:
  https://www.law.cornell.edu/cfr/text/14/23.1322
  https://www.faa.gov/documentLibrary/media/Advisory_Circular/AC_25.1322-1.pdf section 6
]]--
local uavcan_node_Health_1_0 = require('uavcan.node.Health_1_0')
--[[
The operating mode of a node.
Reserved values can be used in future revisions of the specification.
]]--
local uavcan_node_Mode_1_0 = require('uavcan.node.Mode_1_0')


-- constants
local MAX_PUBLICATION_PERIOD = 1
local OFFLINE_TIMEOUT = 3
local PORT_ID = 7509
local BIT_EXTENT = 96
local EXTENT = BIT_EXTENT / 8

-- constituent fields
--[[
[second]
The uptime seconds counter should never overflow. The counter will reach the upper limit in ~136 years,
upon which time it should stay at 0xFFFFFFFF until the node is restarted.
Other nodes may detect that a remote node has restarted when this value leaps backwards.
]]--
local uavcan_node_Heartbeat_1_0_uptime = ProtoField.new(
    'uptime', -- name in the shown fields
    'uavcan.node.Heartbeat_1_0.uptime', -- abbr named used by filters
     ftypes.UINT32) -- field type

--[[
The abstract health status of this node.
]]--
-- CompositeTypes are required above ^

--[[
The abstract operating mode of the publishing node.
This field indicates the general level of readiness that can be further elaborated on a per-activity basis
using various specialized interfaces.
]]--
-- CompositeTypes are required above ^

--[[
Optional, vendor-specific node status code, e.g. a fault code or a status bitmask.
]]--
local uavcan_node_Heartbeat_1_0_vendor_specific_status_code = ProtoField.new(
    'vendor_specific_status_code', -- name in the shown fields
    'uavcan.node.Heartbeat_1_0.vendor_specific_status_code', -- abbr named used by filters
     ftypes.UINT8) -- field type


-- local flag to prevent multiple inclusion
local uavcan_node_Heartbeat_1_0_registered = false

-- Registers the fields of the message to the Proto
-- @param cyphal_proto The Proto to add the fields to
local function register_uavcan_node_Heartbeat_1_0(cyphal_proto)
    if not uavcan_node_Heartbeat_1_0_registered then
        table.insert(cyphal_proto.fields, uavcan_node_Heartbeat_1_0_uptime)
        -- composite types are below
        -- composite types are below
        table.insert(cyphal_proto.fields, uavcan_node_Heartbeat_1_0_vendor_specific_status_code)
        uavcan_node_Health_1_0.register(cyphal_proto)
        uavcan_node_Mode_1_0.register(cyphal_proto)
        uavcan_node_Heartbeat_1_0_registered = true
    end
end

-- Decodes a uavcan_node_Heartbeat_1_0
-- Returns the number of bytes decoded
local function decode_uavcan_node_Heartbeat_1_0(proto, payload, pinfo, payload_tree, label)
    local offset = 0 -- used to track the current byte offset through the decoded packet
    local _delimiter_ = 0 -- this may not be used in all circumstances, check for zero!
    local _length_ = 0 -- used for the length of variable length array
    local field_size = 0 -- used to track the extent of a field or it's _delimiter_ size.
    local extent = 0 -- used to track the current of this type
    if payload:len() <= EXTENT then
        extent = payload:len()
    else
        error("Payload is too large for uavcan.node.Heartbeat_1_0")
        extent = EXTENT
    end
    local subtree = payload_tree:add(proto, payload(0, extent), "uavcan.node.Heartbeat_1_0")
    subtree:prepend_text(string.format("%s of type ", label))

    -- primitive type
    offset = offset + nunavut_support.as_uint32(
            uavcan_node_Heartbeat_1_0_uptime,
            payload(offset, 4),
            pinfo, subtree, "uptime")

    offset = offset + uavcan_node_Health_1_0.decode(
            proto, payload(offset, uavcan_node_Health_1_0.extent),
            pinfo, subtree, "health")

    offset = offset + uavcan_node_Mode_1_0.decode(
            proto, payload(offset, uavcan_node_Mode_1_0.extent),
            pinfo, subtree, "mode")

    -- primitive type
    offset = offset + nunavut_support.as_uint8(
            uavcan_node_Heartbeat_1_0_vendor_specific_status_code,
            payload(offset, 1),
            pinfo, subtree, "vendor_specific_status_code")


    return offset
end

-- Return the decode, register and the option port id
return {
    register = register_uavcan_node_Heartbeat_1_0
    , decode = decode_uavcan_node_Heartbeat_1_0
    , extent = EXTENT
    , subject_id = PORT_ID
}


